version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      # default database
      MYSQL_DATABASE: 'my_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: rootpasswd
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_volume:/var/lib/mysql
    networks: 
      - def_net

  admin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks: 
      - def_net

volumes:
    mysql_volume:

networks:
  def_net:

# Nota: una vez levantado pueden acceder a phpmyadmin desde el browser a http://localhost:8080