version: '3.7'
services:
  webserver:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app_server
    ports:
      - 5005:5005
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks: 
      - frontend
  
  app_server:
    image: my_app_image:latest
    build: app_server/
    restart: unless-stopped
    volumes: 
      - ./app_server/src:/app
    networks:
      - frontend

volumes:
  db_volume:

networks:
  frontend:
